# Generated by edwmurph/codux .github/workflows/publish-homebrew.yml.
class Codux < Formula
  desc "Coordinate multiple Codex sessions from a single tmux workspace"
  homepage "https://github.com/edwmurph/codux"
  url "https://github.com/edwmurph/codux/archive/refs/tags/v3.0.1.tar.gz"
  sha256 "f82325706bf940c4dfafc3d0e6d831963bb5ccab4fa37639ec1926e20e518642"
  license "MIT"

  depends_on "go" => :build
  depends_on "tmux"

  def install
    system "go", "build", "-ldflags", "-X github.com/edwmurph/codux/internal/version.Version=#{version}", "-o", bin/"codux", "./cmd/codux"
  end

  test do
    assert_match "Start, inspect, or close Codux tmux workspaces", shell_output("#{bin}/codux --help")
    assert_match "tmux", shell_output("#{bin}/codux doctor")
  end
end
