# Generated by edwmurph/codux .github/workflows/publish-homebrew.yml.
class Codux < Formula
  desc "Coordinate multiple Codex sessions from a single tmux workspace"
  homepage "https://github.com/edwmurph/codux"
  url "https://github.com/edwmurph/codux/archive/refs/tags/v3.1.0.tar.gz"
  sha256 "2bb6c9bd4bb8b0dc3eeeec2259c62f8d526bdf3c8276e76f9c378af73adb37a9"
  license "MIT"

  depends_on "go" => :build
  depends_on "tmux"

  def install
    system "go", "build", "-ldflags", "-X github.com/edwmurph/codux/internal/version.Version=#{version}", "-o", bin/"codux", "./cmd/codux"
  end

  test do
    assert_match "Start, inspect, or close Codux tmux workspaces", shell_output("#{bin}/codux --help")
    assert_match "tmux", shell_output("#{bin}/codux doctor")
  end
end
