# Generated by edwmurph/weft .github/workflows/publish-homebrew.yml.
class Weft < Formula
  desc "Terminal dashboard for Codex agent threads"
  homepage "https://github.com/edwmurph/weft"
  url "https://github.com/edwmurph/weft/archive/refs/tags/v7.0.1.tar.gz"
  sha256 "21b535cefb63ce65c77d4483b3403be99754af1aa308e63b77dcc07eea7aae5d"
  license "MIT"

  depends_on "go" => :build

  def install
    system "go", "build", "-ldflags", "-X github.com/edwmurph/weft/internal/version.Version=#{version} -X github.com/edwmurph/weft/internal/version.BuildChannel=release", "-o", bin/"weft", "./cmd/weft"
  end

  test do
    ENV["WEFT_HOME"] = testpath/"weft-home"
    ENV["WEFT_WORKSPACE"] = testpath
    assert_match "Terminal dashboard for Codex agent threads", shell_output("#{bin}/weft --help")
    assert_match "supervisor owns Codex PTYs", shell_output("#{bin}/weft doctor")
  end
end
