# Generated by edwmurph/weft .github/workflows/publish-homebrew.yml.
class Weft < Formula
  desc "Terminal dashboard for Codex and shell tasks"
  homepage "https://github.com/edwmurph/weft"
  url "https://github.com/edwmurph/weft/archive/refs/tags/v0.11.2.tar.gz"
  sha256 "046c5ad8cf6fdbe741eaf942fc07976e2ca99a1bb15ca989e1f19819a3eff3d5"
  license "MIT"

  depends_on "go" => :build

  def install
    system "go", "build", "-ldflags", "-X github.com/edwmurph/weft/internal/version.Version=#{version} -X github.com/edwmurph/weft/internal/version.BuildChannel=release", "-o", bin/"weft", "./cmd/weft"
  end

  test do
    ENV["WEFT_ROOT"] = testpath
    assert_match "Terminal dashboard for Codex and shell tasks", shell_output("#{bin}/weft --help")
    assert_match "supervisor owns task PTYs", shell_output("#{bin}/weft doctor")
  end
end
